# -*- coding: utf-8 -*-
"""
Created on Tue Oct 21 15:33:09 2025

@author: SD 1
"""

# -*- coding: utf-8 -*-
"""
Created on Mon Oct 20 15:33:25 2025

@author: Luche Louw
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pandas.api.types import CategoricalDtype

#==============================================================================
#Question 1 – Data Cleaning & Preparation (20 marks)
#==============================================================================

df = pd.read_csv('C:/Users/SD 1/Downloads/istanbul_sales_data.csv.csv')

# getting general insight and overview of my data 
df.info()
print(df.head())
print(df.describe())

df =df.dropna()
print(df.isnull().sum())
df = df.drop_duplicates()

#here i am dropping rows where price or quaninty equals 0
df = df[~((df['quantity'] <= 0) | (df['price'] <= 0 ))]
print(df.shape)

#making a new column , calculating the revenue
df['revenue'] = df['quantity'] * df['price']

# changing the invoice_date , column from and object to datetime
df['invoice_date'] = pd.to_datetime(df['invoice_date'])

#==============================================================================
#Question 2 – Exploratory Data Analysis (30 marks)
#==============================================================================

# frequency table for ,payment_method , gender, category ,shopping_mall
paymethod_freq=df['payment_method'].value_counts()
print(paymethod_freq)

gender_freq = df['gender'].value_counts()
print(gender_freq)

category_freq = df['category'].value_counts()
print(category_freq)
shopping_mall_freq = df['shopping_mall'].value_counts()
print(shopping_mall_freq)

#creating age groups

bins = [0,20,30,40,50,60,70,float('inf')]
# the bins defines the edges/boundaries for each age group
labels = ['0-20' , '21-30' , '31-40' , '41-50' , '51-60','61-70','71+']
# the label names each age group
df['age_group'] =  pd.cut(df['age'],
                       bins = bins ,
                       labels = labels, 
                       right = True) #means the upper edge is included

ordered_age = CategoricalDtype(categories = ['0-20' , '21-30' , '31-40' ,
                                       '41-50' , '51-60','61-70','71+'] , ordered = True )
df['age_group'] = df['age_group'].astype(ordered_age)
 
age_group_freq = df['age_group'].value_counts().sort_index()
print(age_group_freq)

age_revenue = df.groupby('age_group', observed = False)['revenue'].sum().sort_values(ascending = False)
print(age_revenue)

#==============================================================================
#Question 3 – Visualization (30 marks)
#==============================================================================

#Bar chart: Total revenue per shopping mall.
shoppingmall_revenue = df.groupby('shopping_mall')['revenue'].sum().reset_index()
print(shoppingmall_revenue)

plt.figure(figsize= (7,6))
plt.bar(shoppingmall_revenue['shopping_mall'],
        shoppingmall_revenue['revenue'],
        color = 'purple')

plt.title('Total revenue per shopping mall')
plt.xlabel('Shopping Mall')
plt.ylabel('Total Revenue')

plt.xticks(rotation = 45)
plt.tight_layout()
plt.show()

#Pie chart: Payment method distribution.
# And finding the revenue generated by each payment method group
paymethod_revenue = df.groupby('payment_method')['revenue'].sum().reset_index()
print(paymethod_revenue)

plt.figure(figsize=(10,15))
plt.pie(paymethod_freq,
        labels = paymethod_freq.index,
       autopct='%1.1f%%')
plt.title('The Payment Method Distribution')
plt.show()

#Line chart: Total revenue over time (monthly or daily).

df['year'] = df['invoice_date'].dt.year
df['month'] = df['invoice_date'].dt.month
monthly_revenue = df.groupby(['year', 'month'])['revenue'].sum().reset_index()
print(monthly_revenue)

#making two seperate variable for the year 2023 and 2024
revenue_2023 = monthly_revenue[monthly_revenue['year'] == 2023]
revenue_2024 = monthly_revenue[monthly_revenue['year'] == 2024]

plt.figure(figsize = (12,6))

plt.plot(revenue_2023['month'],
         revenue_2023['revenue'],
         marker = 'o',
         label = '2023' ,
         color = 'orange')
# the monthly revenue for 2023 , will be represented by a orange line

plt.plot(revenue_2024['month'],
         revenue_2024['revenue'],
         marker='o' , 
         color ='blue')
# the monthly revenue for the year 2024 be represented by a blue line 

plt.title("Monthly Revenue of the years 2023 & 2024")
plt.xlabel('Months')
plt.ylabel('Revenue')

months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

plt.xticks(range(1,13), labels = months)
plt.legend(loc = 'best')
plt.grid(True)
plt.show()

#Histogram: Distribution of customer ages.

plt.figure(figsize=(10,6))

plt.bar(age_group_freq.index.astype(str),
         age_group_freq.values,
         color = 'purple')

plt.title('Distribution of customer ages')
plt.xlabel('Customer Age Group')
plt.ylabel('Amount')
plt.show()

#Scatter plot: Customer age vs. total revenue

sns.set_style('whitegrid')
plt.figure(figsize = (5,4))
sns.scatterplot( x = 'age_group' ,
                y = 'revenue' ,
                hue = 'revenue' ,
                size = 'revenue' ,
                data = df)
plt.title('Customer age vs. total revenue')
plt.show()

#==============================================================================
#Question 4 – Insights & Analysis (20 marks)
#==============================================================================
category_revenue = df.groupby('category')['revenue'].sum().sort_values(ascending = False)
print(category_revenue.head(3))

print(age_revenue.head(1))

